// LOGIN
export const FETCH_SIGNIN = "FETCH_SIGNIN";
export const FETCH_SIGNIN_SUCCEEDED = "FETCH_SIGNIN_SUCCEEDED";
export const FETCH_SIGNIN_FAILED = "FETCH_SIGNIN_FAILED";
// LOGOUT
export const FETCH_LOGOUT = "FETCH_LOGOUT";
export const FETCH_LOGOUT_SUCCEEDED = "FETCH_LOGOUT_SUCCEEDED";

// NOTICEBOARD
export const FETCH_NOTICEBOARD = "FETCH_NOTICEBOARD";
export const FETCH_NOTICEBOARD_SUCCEEDED = "FETCH_NOTICEBOARD_SUCCEEDED";
export const FETCH_NOTICEBOARD_FAILED = "FETCH_NOTICEBOARD_FAILED";
export const FETCH_MORE_NOTICEBOARD = "FETCH_MORE_NOTICEBOARD";
export const FETCH_MORE_NOTICEBOARD_SUCCEEDED = "FETCH_MORE_NOTICEBOARD_SUCCEEDED";

//INFO
export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_USER_INFO_SUCCEEDED = "FETCH_USER_INFO_SUCCEEDED";
export const FETCH_USER_INFO_FAILED = "FETCH_USER_INFO_FAILED";




